networks:
  mqtt_net:
  rabbitmq_net:
  redis_net:

services:
  emqx:
    image: emqx/emqx:latest
    ports:
      - "1883:1883" # tcp port
      - "18083:18083" # Dashboard

  # rabbitmq:
  #   image: rabbitmq:4-management
  #   ports:
  #     - "5672:5672"
  #     - "15672:15672" # Dashboard

  redis:
    image: redis:8.2
    ports:
      - 6379:6379

  redis-insight:
    image: redis/redisinsight:latest
    ports:
      - 5540:5540 #Dashboard
    depends_on:
      - redis

  transmitter:
    build:
      context: ./transmitter
      dockerfile: Dockerfile
    environment:
      - MQTT_ADDRESS=emqx
      - MQTT_PORT=1883
      - MQTT_TOPIC=loggers
      - COUNT=100
      - INTERVAL=30
    depends_on:
      - emqx

  injestion-service:
    build:
      context: ./services/injestion-service
      dockerfile: Dockerfile
    environment:
      - MQTT_ADDRESS=emqx
      - MQTT_PORT=1883
      - MQTT_TOPIC=loggers
      - MQTT_CLIENT_ID=injestion
      - REDIS_URL=redis:6379
    depends_on:
      - emqx
      - redis

  billing-service:
    build:
      context: ./services/billing-service
      dockerfile: Dockerfile
    environment:
      - REDIS_URL=redis:6379
    depends_on:
      - redis
